name = "skill-hub"
main = "src/index.ts"
compatibility_date = "2025-08-25"
compatibility_flags = ["nodejs_compat"]

account_id = "f15741cdd7efe307679ea99df9da5582"
workers_dev = true

[[kv_namespaces]]
binding = "SKILL_CACHE"
id = "42bca62b834d4153a873f1b0bc0c68b1"

[vars]
GITHUB_REPO = "alanzeng423/skill-hub"
GITHUB_BRANCH = "main"
SKILLS_PATH = "skills"

[[routes]]
pattern = "skill.alanzeng.com"
custom_domain = true
zone_name = "alanzeng.com"
